# Generated by Django 5.0.7 on 2024-07-28 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('IdPais', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('FechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('LimiteCredito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pais', verbose_name='IdPais')),
            ],
        ),
    ]
