# Generated by Django 5.0.7 on 2024-07-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_pais_idpais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='IdPais',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
