# Generated by Django 5.0.7 on 2024-07-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pais_idpais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='Nombre',
            field=models.CharField(max_length=40),
        ),
    ]
