# Generated by Django 5.0.7 on 2024-07-30 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_pais_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pais'),
        ),
    ]
