# Generated by Django 5.0.7 on 2024-07-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_empleado_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='FechaIngreso',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
